server:
  servlet:
    context-path: /com.trinity.dev.user.gateway
  port: 8010
spring:
  profiles:
    active: test # test server configuration
  application: 
    name: com.trinity.dev.gateway
  jmx:
    default-domain: com.trinity.dev.gateway
  main:
    allow-bean-definition-overriding: true
logging:
  pattern:
      file: "%d %-5level [%thread] %logger{0} : %msg%n"
  level:
    org.springframework.web: DEBUG
    guru.springframework.controllers: DEBUG
#    org.hibernate: DEBUG
    org.springframework.security.oauth2: debug
camel:
  springboot::
    shutdownTimeout: 1
    health.indicator.enabled: true
#    xmlRoutes: false
    xmlRoutes: classpath:META-INF/camel/*.xml
    jmxEnabled: false
info.app.name: OAuth-SSO
info.app.description: OAuth - Single Sign On platform
info.app.version: 1.0.0
---
spring:
  profiles: localhost
rest:
  ml:
    method: POST
    contentType: application/json
    uri: https://us-central1-risk-tensor-flow-258320.cloudfunctions.net/risk-tf
---
spring:
  profiles: test
rest:
  ml:
    uri: https://us-central1-risk-tensor-flow-258320.cloudfunctions.net/risk-tf